---

- name: Ensure /etc/osbuild-composer exists
  file:
    path: /etc/osbuild-composer
    state: directory

- name: Get CA certificate from S3
  aws_s3:
    mode: get
    bucket: imagebuilder-deployment
    object: ca-crt.pem
    dest: /etc/osbuild-composer/ca-crt.pem

- name: Get CA key from S3
  aws_s3:
    mode: get
    bucket: imagebuilder-deployment
    object: ca-crt.key
    dest: /tmp/ca-crt.key

- name: Create private key
  openssl_privatekey:
    path: "/etc/osbuild-composer/{{ node_type }}-key.pem"
    size: 4096
    owner: _osbuild-composer
  become: yes

- name: Create CSR
  openssl_csr:
    path: "/tmp/{{ node_type }}.csr"
    privatekey_path: "/etc/osbuild-composer/{{ node_type }}-key.pem"
    digest: sha512
    subject:
      commonName: "{{ ansible_hostname }}"
    owner: _osbuild-composer
  become: yes

- name: Sign certificate
  openssl_certificate:
    csr_path: "/tmp/{{ node_type }}.csr"
    path: "/etc/osbuild-composer/{{ node_type }}-crt.pem"
    privatekey_path: "/etc/osbuild-composer/{{ node_type }}-key.pem"
    ownca_path: /etc/osbuild-composer/ca-crt.pem
    ownca_privatekey_path: /tmp/ca-crt.key
    provider: ownca
    owner: _osbuild-composer
  become: yes

- name: Remove the CA key
  file:
    path: /tmp/ca-crt.key
    state: absent