---

- name: Wait for EBS storage to connect
  wait_for:
    path: "{{ ebs_storage_device }}"
    timeout: 300

- name: Check for XFS filesystem on EBS storage
  command: "xfs_info {{ ebs_storage_device }}"
  failed_when: no
  register: filesystem_check

- name: Create XFS filesystem on EBS storage
  command: mkfs.xfs "{{ ebs_storage_device }}"
  when: filesystem_check.rc != 0

- name: Ensure osbuild-composer directory exists
  file:
    path: /var/lib/osbuild-composer
    state: directory

- name: Mount EBS volume
  mount:
    src: "{{ ebs_storage_device }}"
    path: /var/lib/osbuild-composer
    fstype: xfs
    opts: defaults
    state: mounted

- name: Ensure SELinux contexts are set
  command: restorecon -Rv /var/lib/

- name: Set permissions on the mounted volume
  file:
    path: /var/lib/osbuild-composer
    owner: _osbuild_composer
    group: _osbuild_composer
    state: directory

- name: Verify that the storage is writable
  file:
    path: /var/lib/osbuild-composer/.ansible_check
    state: "{{ item }}"
  loop:
    - touch
    - absent