# A simple CI job to verify our terraform plan.
# Docs: https://www.terraform.io/docs/github-actions/setup-terraform.html

name: Deploy to AWS

on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  deploy:
    name: "🚀"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_RHN_REGISTRATION_USERNAME: ${{ secrets.TF_VAR_RHN_REGISTRATION_USERNAME }}
      TF_VAR_RHN_REGISTRATION_PASSWORD: ${{ secrets.TF_VAR_RHN_REGISTRATION_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=deployment-plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve deployment-plan